name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        cd Scarlett-Sideloader
        dotnet restore
    - name: Build
      run: |
        cd Scarlett-Sideloader
        dotnet publish -c Release --no-restore -o release.${GITHUB_SHA::6}
        tar czvf "release.${GITHUB_SHA::6}.tar.gz" "release.${GITHUB_SHA::6}"    
    - name: Test
      run: |
        cd Scarlett-Sideloader
        dotnet test --no-build --verbosity normal
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: ../worker/Scarlet-Sideloader/Scarlet-Sideloader/Scarlett-Sideloader/release.${GITHUB_SHA::6}.tar.gz
