name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        cd Scarlett-Sideloader
        dotnet restore
    - name: Build
      run: |
        cd Scarlett-Sideloader
        dotnet publish -c Release --no-restore -o ${GITHUB_SHA}
        tar czvf "${GITHUB_SHA}.tar.gz" "${GITHUB_SHA}"    
    - name: Test
      run: |
        cd Scarlett-Sideloader
        dotnet test --no-build --verbosity normal
    #- name: Upload artifact
    #  run: |
    #    cd Scarlett-Sideloader
    #    ls
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: "Scarlett-Sideloader/${{GITHUB.SHA}}.tar.gz"
